name: petrescue
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^6.0.5
  rxdart: ^0.24.1
  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5755
  flutter_signin_button: ^1.1.0
  google_fonts: ^1.1.0
  email_validator: '^1.0.5'
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.4
  equatable: ^1.2.5
  meta: ^1.1.8
  pedantic: ^1.9.0
  formz: ^0.2.0
  flutter_typeahead: "^1.8.8"
  collection: ">=1.14.11 <2.0.0"
  image_picker: ^0.6.7+12
  flutter_custom_dialog: ^1.0.20
  path_provider: ^1.6.21

  bloc: ^6.0.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/mdi_perm_identity.png
    - lib/assets/mdi_pets.png
    - lib/assets/mdi_rss_feed.png
    - lib/assets/mdi_settings.png
    - lib/assets/profile_icon.png
    - lib/assets/placeholder_post_img.png
    - lib/assets/template_cat.png
    - lib/assets/landing_page_pets.png
    - lib/assets/landing_page_woman.png
    - lib/assets/paw.png
    - lib/assets/contact.png
    - lib/assets/cat3.png
    - lib/assets/cat4.png
    - lib/assets/dog.jpg
    - lib/assets/paw-dog.png
    - lib/assets/petfamily.png
    - lib/assets/facebook_new.png
    - lib/assets/google_light.png
    - lib/assets/tracking_page.png
    - lib/assets/truck.png
    - lib/assets/noti_unread.png
    - lib/assets/setting_icon.png
    - lib/assets/rescue_center_logo.jpg
    - lib/assets/Cat2.png
    - lib/assets/Cat3.png
    - lib/assets/someone1.png
    - lib/assets/rescueCenterLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages